language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - npm install
  - npm install -g grunt-cli
script:
  - grunt jshint  # run jshint
  - python centralserver/manage.py test
  - python ka-lite/python-packages/fle_utils/tests.py  # ka-lite regressions
  - python ka-lite/kalite/manage.py test
notifications:
  email:
    - ben@learningequality.org
